driver:
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    axes:
        leftTrigger: yeetShot
        rightTrigger: slowMode
    dpad:
        left: turretJogLeft
        right: turretJogRight
    buttons:
        leftBumper: toggleCollector
        rightBumper: toggleCollectorReverse
        start: zeroPose
operator:
    rumble: false
    joysticks:
        left:
            horizontal: manualTurretXVal
            vertical: manualTurretYVal
        right:
            vertical: manualClimberArm
    dpad:
        up: raiseBucket
        down: lowerBucket
    buttonpad:
        y: autoClimb
    buttons:
        leftBumper: autoAim
        rightBumper: toggleHood
        start: toggleTopClamp
        back: toggleBottomClamp
